const europeanCountries = [
    { name: 'Austria', code: 'AT', flag: 'https://flagcdn.com/w320/at.png' },
    { name: 'Belgium', code: 'BE', flag: 'https://flagcdn.com/w320/be.png' },
    { name: 'Bulgaria', code: 'BG', flag: 'https://flagcdn.com/w320/bg.png' },
    { name: 'Croatia', code: 'HR', flag: 'https://flagcdn.com/w320/hr.png' },
    { name: 'Cyprus', code: 'CY', flag: 'https://flagcdn.com/w320/cy.png' },
    { name: 'Czech Republic', code: 'CZ', flag: 'https://flagcdn.com/w320/cz.png' },
    { name: 'Denmark', code: 'DK', flag: 'https://flagcdn.com/w320/dk.png' },
    { name: 'Estonia', code: 'EE', flag: 'https://flagcdn.com/w320/ee.png' },
    { name: 'Finland', code: 'FI', flag: 'https://flagcdn.com/w320/fi.png' },
    { name: 'France', code: 'FR', flag: 'https://flagcdn.com/w320/fr.png' },
    { name: 'Germany', code: 'DE', flag: 'https://flagcdn.com/w320/de.png' },
    { name: 'Greece', code: 'GR', flag: 'https://flagcdn.com/w320/gr.png' },
    { name: 'Hungary', code: 'HU', flag: 'https://flagcdn.com/w320/hu.png' },
    { name: 'Iceland', code: 'IS', flag: 'https://flagcdn.com/w320/is.png' },
    { name: 'Ireland', code: 'IE', flag: 'https://flagcdn.com/w320/ie.png' },
    { name: 'Italy', code: 'IT', flag: 'https://flagcdn.com/w320/it.png' },
    { name: 'Latvia', code: 'LV', flag: 'https://flagcdn.com/w320/lv.png' },
    { name: 'Lithuania', code: 'LT', flag: 'https://flagcdn.com/w320/lt.png' },
    { name: 'Luxembourg', code: 'LU', flag: 'https://flagcdn.com/w320/lu.png' },
    { name: 'Malta', code: 'MT', flag: 'https://flagcdn.com/w320/mt.png' },
    { name: 'Netherlands', code: 'NL', flag: 'https://flagcdn.com/w320/nl.png' },
    { name: 'Norway', code: 'NO', flag: 'https://flagcdn.com/w320/no.png' },
    { name: 'Poland', code: 'PL', flag: 'https://flagcdn.com/w320/pl.png' },
    { name: 'Portugal', code: 'PT', flag: 'https://flagcdn.com/w320/pt.png' },
    { name: 'Romania', code: 'RO', flag: 'https://flagcdn.com/w320/ro.png' },
    { name: 'Slovakia', code: 'SK', flag: 'https://flagcdn.com/w320/sk.png' },
    { name: 'Slovenia', code: 'SI', flag: 'https://flagcdn.com/w320/si.png' },
    { name: 'Spain', code: 'ES', flag: 'https://flagcdn.com/w320/es.png' },
    { name: 'Sweden', code: 'SE', flag: 'https://flagcdn.com/w320/se.png' },
    // { name: 'Switzerland', code: 'CH', flag: 'https://flagcdn.com/w320/ch.png' },
    // Add more countries as needed
];

export default europeanCountries;
